# Generated by Django 4.2.11 on 2026-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_configuration_storage2_storage3'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcpart',
            name='base_clock_mhz',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='boost_clock_mhz',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='capacity_gb',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='chipset',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='cores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='currency',
            field=models.CharField(default='JPY', max_length=3),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='dospara_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='efficiency_grade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='form_factor',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='included_fan_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='interface',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='license_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='m2_slots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='maker',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='max_tdp_w',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='memory_type',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='model_code',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='os_edition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='os_family',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='pcie_x16_slots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='socket',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='speed_mhz',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='stock_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='supported_fan_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='tdp_w',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='threads',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='type_c_ports',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='usb_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='vram_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='vram_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='wattage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
