# Generated by Django 4.2.11 on 2026-04-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_alter_configuration_usage_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='usage',
            field=models.CharField(choices=[('gaming', 'Gaming'), ('creator', 'Creator'), ('business', 'Business'), ('standard', 'Standard'), ('video_editing', 'Workstation')], max_length=20),
        ),
    ]
