# Generated by Django 4.2.11 on 2026-03-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_backfill_pcpart_normalized_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_gb', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('interface', models.CharField(blank=True, db_index=True, max_length=30)),
                ('form_factor', models.CharField(blank=True, db_index=True, max_length=30)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_detail', to='scraper.pcpart')),
            ],
        ),
        migrations.CreateModel(
            name='PSUDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wattage', models.PositiveIntegerField(blank=True, null=True)),
                ('efficiency_grade', models.CharField(blank=True, max_length=20)),
                ('form_factor', models.CharField(blank=True, db_index=True, max_length=30)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psu_detail', to='scraper.pcpart')),
            ],
        ),
        migrations.CreateModel(
            name='OSDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_family', models.CharField(blank=True, max_length=30)),
                ('os_edition', models.CharField(blank=True, max_length=50)),
                ('license_type', models.CharField(blank=True, max_length=30)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='os_detail', to='scraper.pcpart')),
            ],
        ),
        migrations.CreateModel(
            name='MotherboardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(blank=True, db_index=True, max_length=50)),
                ('memory_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('chipset', models.CharField(blank=True, db_index=True, max_length=50)),
                ('form_factor', models.CharField(blank=True, db_index=True, max_length=30)),
                ('m2_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('pcie_x16_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('usb_total', models.PositiveIntegerField(blank=True, null=True)),
                ('type_c_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_detail', to='scraper.pcpart')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('capacity_gb', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('speed_mhz', models.PositiveIntegerField(blank=True, null=True)),
                ('form_factor', models.CharField(blank=True, db_index=True, max_length=30)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_detail', to='scraper.pcpart')),
            ],
        ),
        migrations.CreateModel(
            name='GPUDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('vram_type', models.CharField(blank=True, max_length=20)),
                ('tdp_w', models.PositiveIntegerField(blank=True, null=True)),
                ('interface', models.CharField(blank=True, db_index=True, max_length=30)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_detail', to='scraper.pcpart')),
            ],
        ),
        migrations.CreateModel(
            name='CPUDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(blank=True, db_index=True, max_length=50)),
                ('memory_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('cores', models.PositiveIntegerField(blank=True, null=True)),
                ('threads', models.PositiveIntegerField(blank=True, null=True)),
                ('tdp_w', models.PositiveIntegerField(blank=True, null=True)),
                ('base_clock_mhz', models.PositiveIntegerField(blank=True, null=True)),
                ('boost_clock_mhz', models.PositiveIntegerField(blank=True, null=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_detail', to='scraper.pcpart')),
            ],
        ),
        migrations.CreateModel(
            name='CPUCoolerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(blank=True, db_index=True, max_length=50)),
                ('max_tdp_w', models.PositiveIntegerField(blank=True, null=True)),
                ('form_factor', models.CharField(blank=True, db_index=True, max_length=30)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_cooler_detail', to='scraper.pcpart')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_factor', models.CharField(blank=True, db_index=True, max_length=30)),
                ('included_fan_count', models.PositiveIntegerField(blank=True, null=True)),
                ('supported_fan_count', models.PositiveIntegerField(blank=True, null=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_detail', to='scraper.pcpart')),
            ],
        ),
    ]
