# Generated by Django 4.2.11 on 2026-03-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_backfill_part_details_2nf'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfficiencyGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OSEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OSFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='casedetail',
            name='form_factor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_details', to='scraper.formfactor'),
        ),
        migrations.AddField(
            model_name='cpucoolerdetail',
            name='form_factor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_cooler_details', to='scraper.formfactor'),
        ),
        migrations.AddField(
            model_name='cpucoolerdetail',
            name='socket_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_cooler_details', to='scraper.sockettype'),
        ),
        migrations.AddField(
            model_name='cpudetail',
            name='memory_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_details', to='scraper.memorytype'),
        ),
        migrations.AddField(
            model_name='cpudetail',
            name='socket_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_details', to='scraper.sockettype'),
        ),
        migrations.AddField(
            model_name='gpudetail',
            name='interface_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpu_details', to='scraper.interfacetype'),
        ),
        migrations.AddField(
            model_name='memorydetail',
            name='form_factor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_details', to='scraper.formfactor'),
        ),
        migrations.AddField(
            model_name='memorydetail',
            name='memory_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_details', to='scraper.memorytype'),
        ),
        migrations.AddField(
            model_name='motherboarddetail',
            name='form_factor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motherboard_details', to='scraper.formfactor'),
        ),
        migrations.AddField(
            model_name='motherboarddetail',
            name='memory_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motherboard_details', to='scraper.memorytype'),
        ),
        migrations.AddField(
            model_name='motherboarddetail',
            name='socket_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motherboard_details', to='scraper.sockettype'),
        ),
        migrations.AddField(
            model_name='osdetail',
            name='license_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_details', to='scraper.licensetype'),
        ),
        migrations.AddField(
            model_name='osdetail',
            name='os_edition_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_details', to='scraper.osedition'),
        ),
        migrations.AddField(
            model_name='osdetail',
            name='os_family_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_details', to='scraper.osfamily'),
        ),
        migrations.AddField(
            model_name='pcpart',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='scraper.manufacturer'),
        ),
        migrations.AddField(
            model_name='psudetail',
            name='efficiency_grade_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psu_details', to='scraper.efficiencygrade'),
        ),
        migrations.AddField(
            model_name='psudetail',
            name='form_factor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psu_details', to='scraper.formfactor'),
        ),
        migrations.AddField(
            model_name='storagedetail',
            name='form_factor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_details', to='scraper.formfactor'),
        ),
        migrations.AddField(
            model_name='storagedetail',
            name='interface_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_details', to='scraper.interfacetype'),
        ),
    ]
