# Generated by Django 4.2.11 on 2026-04-04 03:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(db_index=True, max_length=80)),
                ('source_url', models.URLField()),
                ('updated_at_source', models.CharField(blank=True, max_length=40)),
                ('score_note', models.CharField(blank=True, max_length=200)),
                ('parser_version', models.CharField(default='v1', max_length=30)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='GPUPerformanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_name', models.CharField(max_length=120)),
                ('model_key', models.CharField(db_index=True, max_length=80)),
                ('vendor', models.CharField(choices=[('nvidia', 'NVIDIA'), ('amd', 'AMD'), ('intel', 'Intel'), ('igpu', 'iGPU'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('vram_gb', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('perf_score', models.PositiveIntegerField()),
                ('detail_url', models.URLField(blank=True)),
                ('is_laptop', models.BooleanField(db_index=True, default=False)),
                ('rank_global', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scraper.gpuperformancesnapshot')),
            ],
            options={
                'ordering': ['-perf_score', 'gpu_name'],
                'unique_together': {('snapshot', 'model_key', 'vram_gb', 'is_laptop')},
            },
        ),
    ]
