# Generated by Django 4.2.11 on 2026-04-05 10:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_gpuperformancesnapshot_gpuperformanceentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUSelectionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(db_index=True, max_length=80)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('exclude_intel_13_14', models.BooleanField(default=True)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('excluded_count', models.PositiveIntegerField(default=0)),
                ('parser_version', models.CharField(default='v1', max_length=30)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='CPUSelectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(db_index=True, max_length=20)),
                ('model_name', models.CharField(max_length=120)),
                ('perf_score', models.PositiveIntegerField()),
                ('source_url', models.URLField(blank=True)),
                ('rank_global', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scraper.cpuselectionsnapshot')),
            ],
            options={
                'ordering': ['-perf_score', 'model_name'],
                'unique_together': {('snapshot', 'model_name')},
            },
        ),
    ]
