# Generated by Django 4.2.11 on 2026-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_remove_configuration_memo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
