# Generated by Django 4.2.11 on 2026-04-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0020_configuration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcpart',
            name='part_type',
            field=models.CharField(choices=[('cpu', 'CPU'), ('cpu_cooler', 'CPU Cooler'), ('gpu', 'GPU'), ('motherboard', 'Motherboard'), ('memory', 'Memory'), ('storage', 'Storage'), ('os', 'OS'), ('psu', 'Power Supply'), ('case', 'Case'), ('case_fan', 'Case Fan')], max_length=20),
        ),
    ]
