# Generated by Django 4.2.11 on 2026-04-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0021_add_case_fan_part_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcpart',
            old_name='dospara_code',
            new_name='shop_code',
        ),
    ]
