# Generated by Django 4.2.11 on 2026-04-29 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0022_rename_dospara_code_to_shop_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='case_fan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfg_case_fan', to='scraper.pcpart'),
        ),
    ]
