# Generated by Django 4.2.11 on 2026-05-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_pcpart_missing_fields_state_only'),
        ('scraper', '0024_storagedetail_storage_category'),
    ]

    operations = [
    ]
